// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations (DDL) preferem a conexão DIRECT (sem pgbouncer/-pooler):
    // o pooler do Neon em transaction mode quebra advisory locks que o
    // `prisma migrate` usa. Runtime continua na pooled (ver src/lib/prisma.ts).
    // Fallback p/ DATABASE_URL mantém o dev local (sem pooler) funcionando.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
